version: '3'

services:

  init_es_data:
    image: alpine
    container_name: init_es_data
    volumes:
      - es_data:/backup_volume  
      - ./es_data_backup_2024-10-26.tgz:/backup/es_data_backup.tgz
    command: >
      sh -c "if [ -z \"$(ls -A /backup_volume)\" ]; then
               echo 'Restoring backup to es_data volume...';
               tar -xzf /backup/es_data_backup.tgz -C /backup_volume;
               echo 'Restoration complete.';
             else
               echo 'es_data volume already populated, skipping restore.';
             fi"
    networks:
      - search
    deploy:
      replicas: 0 
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/es_data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - search

  middleware_app:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: middleware
    ports:
      - "5000:5000"  
    networks:
      - search

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile  
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - search
  
  ingest_app:
    build:
      context: ./services/ingest
      dockerfile: Dockerfile
    container_name: ingest
    depends_on:
      - elasticsearch
    networks:
      - search

volumes:
  es_data:
    driver: local

networks:
  search:
    driver: bridge
